wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709700833.499702
    t:
      1:
      - 1
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      2:
      - 1
      - 11
      - 12
      - 41
      - 45
      - 49
      - 51
      - 55
      - 71
      - 83
      - 98
      3:
      - 23
      4: 3.10.13
      5: 0.16.3
      6: 4.38.2
      8:
      - 5
      13: linux-x86_64
decoder_model_path:
  desc: null
  value: /home/mlfavorfit/Desktop/lib_link/favorfit/kjg/0_model_weights/diffusion/Kandinsky/kandinsky-inpainting-controlnet-split
prior_model_path:
  desc: null
  value: /home/mlfavorfit/Desktop/lib_link/favorfit/kjg/0_model_weights/diffusion/Kandinsky/kandinsky-prior
train_data_dir:
  desc: null
  value: /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint
val_prompts:
  desc: null
  value:
  - a watch on green grass
  - a tall bird with a tennis racket
val_images:
  desc: null
  value:
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/images/a7iii_1594_black.jpg
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/images/a7iii_1789_alarg.jpg
val_masks:
  desc: null
  value:
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/masks/a7iii_1594_black.jpg
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/masks/a7iii_1789_alarg.jpg
val_conds:
  desc: null
  value:
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/conditioning_images/a7iii_1594_black.jpg
  - /media/mlfavorfit/sdb/contolnet_dataset/control_net_train_outpaint/conditioning_images/a7iii_1789_alarg.jpg
seed:
  desc: null
  value: 42
batch_size:
  desc: null
  value: 2
epochs:
  desc: null
  value: 100
lr:
  desc: null
  value: 5.0e-06
use_lr_scheduler:
  desc: null
  value: true
mixed_precision:
  desc: null
  value: fp16
report_to:
  desc: null
  value: wandb
save_ckpt_step:
  desc: null
  value: 10000
resume_ckpt_path:
  desc: null
  value: null
validation_step:
  desc: null
  value: 100
invert_mask:
  desc: null
  value: true
